### ISSUE TITLE
Trivial assignment

### ISSUE THREAD

**Issue by StSav012** [macPimanov/CEB_IV_Fit#2]
The following line is likely erroneous.

https://github.com/macPimanov/CEB_IV_Fit/blob/71c7a83054e93dafa92a436b04bbc910f6082141/IO.cpp#L60

Please correct it or remove the loop.

**Comment by macPimanov** [comment]
Removed the loop

Всего наилучшего,
Д.А. Пиманов


чт, 7 дек. 2023 г. в 19:24, Anton Yablokov ***@***.***>:
